## Reproducability (trying to take random out of random)

In short how a neural network learns:

`start with random number -> tesnor operations -> update random numbers to try and make them better representions of the data -> again -> again -> again ...`

To reduce the randomness in random networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness

In [2]:
import torch

#Create two new tensor
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9941, 0.1503, 0.2627, 0.7367],
        [0.1992, 0.7694, 0.1214, 0.5229],
        [0.3359, 0.0947, 0.8254, 0.8557]])
tensor([[0.0667, 0.3764, 0.9772, 0.2405],
        [0.6219, 0.1857, 0.7807, 0.9236],
        [0.0657, 0.5171, 0.2300, 0.7521]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [3]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running Tensors and PyTorch Objects on GPUs (and making faster computations)
GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardaware + PyTorch working behind the scenes to make everything faster

### 1. Getting a GPU

1. Easiest - Use Google colab for fa free GPU (options to upgrade as well)
2. Use your own - takes a little bit of setup and required the investment of purchasing a GPU, there's lots of options
3. Use cloud computing - GPC, AWS, Azure, these services allow you to rent computers on the cloud and access them

In [4]:
!nvidia-smi

Thu May 25 22:25:13 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.29                 Driver Version: 531.29       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3080       WDDM | 00000000:26:00.0  On |                  N/A |
|  0%   55C    P8               53W / 400W|   2093MiB / 12288MiB |     27%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

# Check for GPU access with PyToch

In [5]:
# check for GPU access with PyTorch
import torch

torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code

E.g. run on GPU if available, else default to CPU

In [6]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [7]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU
The reason we want out tensors/models on the GPU is because using a GPU results in faster computations

In [8]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

#Tensor not on a GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [9]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU


In [10]:
# If tensor is on GPU cant transform it to numpy
# tensor_on_gpu.numpy()

In [11]:
# To fix the gpu tensor with numpy issue we can first set it to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)